### PR TITLE
New OneCanvasRenderer

### PR DESCRIPTION
**Pull request by miguelmoraleda**
Hey @manuelodelain ,

This is the PR we was speaking about. Please take a look in my OneCanvasRenderer implementation. 

Also I added 'x' and 'y' attributes to the animation object, so you can move them inside the canvas. 

Please let me know what do you think about the implementation so I can make that x and y attributes work properly on the existing renderers.

Also I think we could add alpha and scale attributes to the animation objects, so we can better control the animations being rendered on canvas. What do you think about?

Best regards,
Miguel

### CODE REVIEW

**Comment by manuelodelain** [comment]
Hi @miguelmoraleda !

Thanks a lot for your addition.

I think it's great to add properties like `x` and `y`.
The `OneCanvasRenderer` is almost the same that `CanvasRenderer`. Maybe we should just stay with an option for clearing the canvas inside `CanvasRenderer`.

Instead of assigned dynamicaly an `animation` property to the render instance we can just pass as an argument the `SpriteAnim` instance to the renderer (I think it would be more clear). 

+1 for `scale` and `alpha` properties !

**Comment by miguelmoraleda** [comment]
I totally agree with your comments, I'm gonna change those asap. 

Maybe I will include scale and alpha too :)

**Comment by manuelodelain** [comment]
I've updated the code :) 
https://github.com/manuelodelain/sprite-anim/commit/99a53cad87708706478d478d9fc4c69571607827
https://github.com/manuelodelain/sprite-anim/commit/1d1c01ebf46d11e30db04216e30f4716c10f5488

But not for the scale and alpha !

**Comment by miguelmoraleda** [comment]
Yeah, I saw it.. :) Thanks man. I'm gonna implement that alpha. The scale is kind of tricky. We did it once, but we made it works only for scales between 0 and 1. Upscale wasn't working properly. I'm gonna take a look again.

**Pull request merged**
